project:
  type: website

website:
  title: "Jon Cavallie Mester"
  site-url: https://www.cavalliemester.com
  description: "The personal blog of Jon Cavallie Mester."
  navbar:
    background: dark
    right:
      - icon: github
        href: https://github.com/jonmest
      - icon: linkedin
        href: https://www.linkedin.com/in/jon-mester/
format:
  html:
    theme: 
      - yeti
      - custom.scss
   



